KZL-298-allow-user-to-created-computed-fields
kuzzleio/computed-fields-plugin pull request #1
Opened 2018-09-19 11:33 UTC by etrousset

## What does this PR do ?
First version of the computed field plugin for Kuzzle
Allow user to create field in document that are computed using other fields of the same document

### How should this be manually tested?

Download, install, read the doc, run the tests, and have fun with it.

2018-09-19 12:32 UTC, Aschen commented
As we discussed, rather than using eval, here is a solution with only regexp and replace: https://gist.github.com/Aschen/c070ad4ad14a8437b7ab1149c06fc86f

2018-09-20 13:24 UTC, kuzzle commented
<h1>:cucumber: : Cucumber Report</h1><p>  <em>Check this <a href='https://dl.kuzzle.io/tests-report/computed-fields-plugin/1/cucumber-report.html'>link</a></em></p>

2018-09-21 14:30 UTC, etrousset commented
> As we discussed, rather than using eval, here is a solution with only regexp and replace: https://gist.github.com/Aschen/c070ad4ad14a8437b7ab1149c06fc86f
 @Aschen : Done

2018-09-24 15:24 UTC, scottinet requested changes
I still question the usefulness of this plugin, considering that you can do the exact same thing with a much simpler plugin, adding a pipe to API routes that write documents.

2018-09-24 15:24 UTC, scottinet commented on .eslintrc
> +    "ecmaVersion": 8,
Kuzzle supports Node.js 6 and upper. Official plugins should follow these requirements, since they are executed by the same node.js than Kuzzle.

Therefore, you must stick to ES6.

2018-09-24 15:24 UTC, scottinet commented on README.md
> +The purpose of this plugin is to allow one to create fields that are computed from other fields of a document. e.g. considering the following document:
Proposal: `This plugin allows creating computed fields from a document's existing fields.  For instance, considering the following document:`

2018-09-24 15:24 UTC, scottinet commented on README.md
> +you could have a computed field `fullname` defined as `"${name} ${surname}"` and whose value would be `"Michael Romeo"` for previous exemple.
-`for previous exemple`

2018-09-24 15:24 UTC, scottinet commented on README.md
> +The computed fileds are ensted in a `_computedFields` object to avoid collision with document fields, so the final document will be:
ensted?

Do you mean `saved`, or `stored` perhaps?

2018-09-24 15:24 UTC, scottinet commented on README.md
> +| `create`    | Adds or update a computed field to an `index/collection`        |
Add

2018-09-24 15:24 UTC, scottinet commented on README.md
> +You can create or update a computed field using a http `POST` on the route: `http+https://kuzzlehost:kuzzleport/computed-fields/`
on the route => using the route

2018-09-24 15:24 UTC, scottinet commented on README.md
> +For exemple:
example

2018-09-24 15:24 UTC, scottinet commented on README.md
> +The `list` action will return a array of computed fields.
an array

2018-09-24 15:24 UTC, scottinet commented on README.md
> +  .query({
:warning: The current JS SDK is v5, and in that version, `query` does not return a promise: it takes a callback instead

2018-09-24 15:24 UTC, scottinet commented on README.md
> +Do a `POST` on route `http+https://kuzzlehost:kuzzleport/:_id/_delete'` to delete computed field with `_id`
Shouldn't this be a `DELETE` route instead?

Also, the route is incorrect, as the provided ID is not attached to any index or collection arguments. I did see that the generated ID depends on these two arguments, but I find this system fragile.

The route should be: 

`DELETE http+https://kuzzlehost:kuzzleport/_plugin/computed-fields/:index/:collection/:_id`

or:
`DELETE http://<host>:<port>/_plugin/computed-fields/<index>/<collection>/<_id>`

2018-09-24 15:24 UTC, scottinet commented on README.md
> +Do a `GET` on route `http+https://kuzzlehost:kuzzleport/computed-fields/` to get computed field list
Wrong route, it should be: `http+https://kuzzlehost:kuzzleport/_plugin/computed-fields`

Also, I'm quite fond of the standard `<param>` to describe a required parameter. What do you think of describing your routes like that: `http://<host>:<port>/_plugin/computed-fields`

Lastly, I'm uneasy at the possibility given by that plugin to retrieve any and all computed fields, regardless of their index/collection arguments. This bypasses our right system, and this is also against what a HTTP `GET` route should be, meaning a resource retrieval.
To me, the route should be defined like this: `GET http://<host>:<port>/_plugin/computed-fields/<index>/<collection>`

2018-09-24 15:24 UTC, scottinet commented on README.md
> +$ curl  localhost:7512/_plugin/computed-fields/ -H "Content-Type: application/json"
This route is wrong: the body part of an HTTP request should only contain... well... body arguments. And neither `index` nor `collection` are body arguments.

The route should be more like this:

`POST http://<host>:<port>/_plugin/computed-fields/<index>/<collection>`

Or even:

`PUT http://<host>:<port>/_plugin/computed-fields/<index>/<collection>/<name>`
With only the `value` argument remaining in the body part of the request.

2018-09-24 15:24 UTC, scottinet commented on docker/docker-compose.yml
> +    image: kuzzleio/development:${KUZZLE_DOCKER_TAG:-latest}
plugin-dev?

2018-09-24 15:24 UTC, scottinet commented on lib/index.js
> +    this.initStorage()
`initStorage` should be returned to allow Kuzzle to wait for its completion

Also, the `catch` part is unnecessary if you return the initStorage promise: Kuzzle already provides logs if it fails, and it will stop its starting sequence. With your code, Kuzzle will continue to function, which does not seem to be a good thing.

2018-09-24 15:24 UTC, scottinet commented on lib/index.js
> +          delete e[Symbol.for('_kuzzle')]
?

2018-09-24 15:24 UTC, scottinet commented on lib/index.js
> +    sourceFields.forEach((field) => {
unnecessary parens around `field`

2018-09-24 15:24 UTC, scottinet commented on lib/index.js
> +        throw new Error(`Document ${JSON.stringify(document)} doesn't contain field '${fieldname}'`)
Throwing a plain Error will make Kuzzle recast it as a `PluginImplementationError`, but it seems more like a `BadRequestError` to me.
Also, I don't know if this isn't better to simply ignore a missing field instead.

2018-09-24 15:24 UTC, scottinet commented on lib/index.js
> +    for (let field of fields) {
nitpicking: make `field` const.

As this is a nitpicking remark, I won't report any other occurences of it for the remaining of this PR.

2018-09-24 15:24 UTC, scottinet commented on lib/index.js
> +    let reg=/\$\{([\w_$][\w\d_$.]+)\}/g
should be const

2018-09-24 15:24 UTC, scottinet commented on lib/index.js
> +    let sf = []
also const

2018-09-24 15:24 UTC, scottinet commented on lib/index.js
> +        if (typeof request.input.body._computedFields === 'undefined') {
If `_computedFields` is defined and not an object, then the code below will make this plugin crash, forcing Kuzzle to log a `PluginImplementationError` error

2018-09-24 15:24 UTC, scottinet commented on lib/index.js
> +                  const document = {...res.result._source, ...request.input.body}
This doesn't work in node.js 6

2018-09-24 15:24 UTC, scottinet commented on lib/index.js
> +    return Promise.all(promises)
The promise should not be returned if it ends up resolving a callback

2018-09-24 15:24 UTC, scottinet commented on lib/index.js
> +      && request.input.body.index
Inconsistent with Kuzzle API: `index` and `collection` are made available at the following path: `request.input.resource.index` and `request.input.resource.collection`, respectively

2018-09-24 15:24 UTC, scottinet commented on lib/index.js
> +    return Promise.reject('Body must contain the following fields: \'name\', \'index\', \'collection\' and \'value\'')
Use template litterals so you don't have to escape single quotes

2018-09-24 15:24 UTC, scottinet commented on lib/index.js
> +    let _id = request.input.args._id || request.input.resource._id
should be const

2018-09-24 15:24 UTC, scottinet commented on lib/index.js
> +    if (cfs.length === 0) {
Commented out code should be removed

2018-09-24 15:24 UTC, scottinet commented on lib/index.js
> +    const cfs = this.getCollectionConputedFields(index, collection)
missing semicolon

2018-09-24 15:24 UTC, scottinet commented on lib/index.js
> +      total
missing semicolon

2018-09-24 15:24 UTC, scottinet commented on lib/index.js
> +    )
missing semicolon

2018-09-24 15:24 UTC, scottinet commented on lib/index.js
> +      .then((res) => {
unnecessary parens around `res`

2018-09-24 15:24 UTC, scottinet commented on lib/index.js
> +        let documents = res.result.hits.map(e => {return {_id: e._id, body: e._source}})
* should be const
* missing semicolon

Also, you can return an object directly from within an arrow function, using the following syntax:

`const documents = res.result.hits.map(e => ({_id: e._id, body: e_source}}));`

2018-09-24 15:24 UTC, scottinet commented on lib/index.js
> +        scrollId = res.result._scroll_id
missing semicolon

I just noticed that there almost aren't any semicolon in this section of code, so I'll stop reporting this (but they still must be fixed)

I recommend adding eslint using Kuzzle's `.eslintrc.json` configuration file to this project

2018-09-24 15:24 UTC, scottinet commented on lib/index.js
> +      .then((res) => {
unnecessary parens

2018-09-24 15:24 UTC, scottinet commented on lib/index.js
> +      .then((res) => {
ditto

2018-09-24 15:24 UTC, scottinet commented on lib/index.js
> +        return Promise.resolve({updatedDocuments: total})
Inside a promise chain, everything you return is chainable. Thus you don't need to return a new promise, you can simply return `return {updatedDocuments: total};`

2018-09-24 15:24 UTC, scottinet commented on report/index.js
> +var reporter = require('cucumber-html-reporter');
const

2018-09-24 15:24 UTC, scottinet commented on report/index.js
> +var options = {
const

2018-09-24 15:24 UTC, scottinet commented on report/index.js
> +  .then((info) => {
unnecessary parens

2018-09-25 11:23 UTC, ballinette commented on README.md
> +  .query({
... or call `queryPromise` ?

2018-09-25 11:26 UTC, ballinette commented on package.json
> +    "kuzzle-sdk": "git+https://github.com/kuzzleio/sdk-javascript#6-dev",
nitpicking: use `6-beta` version to stay in a more stable release

2018-09-25 11:29 UTC, ballinette commented on package.json
> +    "kuzzle-sdk": "git+https://github.com/kuzzleio/sdk-javascript#6-dev",
but why do you implement your own SDK instance and not use the embedded one that has been introduced in `1.5.0` release (see https://github.com/kuzzleio/kuzzle/pull/1179) ?

2018-09-25 11:32 UTC, ballinette commented on lib/index.js
>  class CorePlugin {
nitpicking: we could rename the plugin class with a more explicit name (`ComputedFiledsPlugin` for instance ?)

2018-09-26 07:17 UTC, etrousset commented on README.md
> +The computed fileds are ensted in a `_computedFields` object to avoid collision with document fields, so the final document will be:
I meant `nested` but `stored` could do also?

2018-09-26 07:25 UTC, scottinet commented on README.md
> +The computed fileds are ensted in a `_computedFields` object to avoid collision with document fields, so the final document will be:
`embedded` would be closer to what you originally meant, otherwise `stored` is fine

2018-09-28 09:21 UTC, etrousset commented on package.json
> +    "kuzzle-sdk": "git+https://github.com/kuzzleio/sdk-javascript#6-dev",
Because I started working on it before this feature was released

2018-10-02 07:55 UTC, scottinet requested changes

2018-10-02 07:55 UTC, scottinet commented on features/support/steps.js
> +var _ = require('lodash')
* should be `const`
* missing semicolon

2018-10-02 07:55 UTC, scottinet commented on features/support/steps.js
> +  rp = require('request-promise')
Trailing semicolons are missing from this entire file.

2018-10-02 07:55 UTC, scottinet commented on features/support/steps.js
> +    let cfName = computedFieldCfg.name
should be `const`

2018-10-02 07:55 UTC, scottinet commented on features/support/steps.js
> +  let cf = this.result.find((e) => _.isMatch(e, JSON.parse(computedField)))
should be `const`

2018-10-02 07:55 UTC, scottinet commented on features/support/steps.js
> +    let cfBody = {
should be `const`

2018-10-02 07:55 UTC, scottinet commented on lib/index.js
> +    let index = request.input.resource.index
should be `const`

Alternatively, you can use destructuring syntax: 
`const {index, collection} = request.input.resource;`

2018-10-02 07:55 UTC, scottinet commented on lib/index.js
> +    let name = request.input.body && request.input.body.name || request.input.args.name
should be `const`

2018-10-02 07:55 UTC, scottinet commented on lib/index.js
> +    let index = request.input.resource.index
see above

2018-10-02 07:55 UTC, scottinet commented on lib/index.js
> +      let elem = JSON.parse(JSON.stringify(e))
should be `const`

2018-10-02 07:55 UTC, scottinet commented on lib/index.js
> +      r.hits.forEach((e)=> p.push(this.computedFieldsRepository.delete(e._id)))
* `p` should be `const`
* unnecessary parens around `e`
* can be simplified with a map:
`const p = r.hits.map(e => this.computedFieldsRepository.delete(e._id));`

2018-10-02 07:55 UTC, scottinet commented
Also, the file `lib/index.js` still needs trailing semicolon added.

2018-10-04 09:35 UTC, Aschen approved these changes

2018-10-04 14:10 UTC, scottinet approved these changes
:+1:

2018-10-04 14:10 UTC, merged